export const LOGIN_ACCEDER_CARGANDO = 'LOGIN_ACCEDER_CARGANDO';
export const LOGIN_ACCEDER_EXITO = 'LOGIN_ACCEDER_EXITO';
export const LOGIN_ACCEDER_ERROR = 'LOGIN_ACCEDER_ERROR';

export const OBTENER_PERFIL_CARGANDO = 'OBTENER_PERFIL_CARGANDO';
export const OBTENER_PERFIL_EXITO = 'OBTENER_PERFIL_EXITO';
export const OBTENER_PERFIL_ERROR = 'OBTENER_PERFIL_ERROR';

export const CERRAR_SESION = 'CERRAR_SESION';
